### ISSUE TITLE
Ensure `RelativeTime` component's text representation is client side computed 

### ISSUE THREAD

**Issue by rithviknishad** [ohcnetwork/leaderboard#422] opened 2024-04-03 06:34 UTC
When relative time is rendered in an statically generated route, the relative value is no longer correct as it does not change based on the time of the request.

**Solution:**
Relative time to be a client component, and representable relative time text to be computed at client side

<img width="982" alt="image" src="https://github.com/coronasafe/leaderboard/assets/25143503/79f0ed05-8a9a-447e-b443-176a29b56de9">

**Comment by Jash2606** [comment] 2024-10-01 13:29
Hey @rithviknishad ,
I'd like to contribute to this issue for Hacktoberfest . Could you please assign it to me?

**Comment by Jash2606** [comment] 2024-10-01 19:34
Hey @rithviknishad,

I'm encountering an issue with my project where the website looks different on the live version compared to my localhost setup.

### Live Version:
![image](https://github.com/user-attachments/assets/2a2b98a6-c136-41aa-8bd3-2c742fd898de)

### Localhost Version:
![Screenshot 2024-10-02 010026](https://github.com/user-attachments/assets/0806f643-1259-4c0c-ae60-d2624acad188)

As you can see, there are discrepancies in the appearance. Could you help me identify the root cause and figure out a solution to make both versions consistent?

**Comment by rithviknishad** [comment] 2024-10-03 04:20
You mean the data present in both is different? Or the layout?

**Comment by Jash2606** [comment] 2024-10-03 06:46
> You mean the data present in both is different? Or the layout?

Both things are different in live version and in localhost

**Comment by rithviknishad** [comment] 2024-10-03 09:17
data being different is likely because your local data-repo is outdated.

layout, I don't see any difference.

**Closed** 2024-10-03 17:08 UTC
Labels: good first issue, hacktoberfest
